AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Process Zip Lambda para Google Drive

Resources:
  ProcessZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
